'use strict';

/**
 * Transfer lifecycle. State changes must be recorded in a local SQLite
 * transaction. FAILED and STORED are terminal, except that FAILED can be
 * retried only through the explicit RECOVERY_PENDING transition.
 */
const TRANSFER_STATE = Object.freeze({
  CREATED: 'CREATED',
  ENCRYPTING: 'ENCRYPTING',
  ENCRYPTED: 'ENCRYPTED',
  RELAY_RECEIVING: 'RELAY_RECEIVING',
  RELAY_VERIFIED: 'RELAY_VERIFIED',
  STORAGE_RECEIVING: 'STORAGE_RECEIVING',
  STORED: 'STORED',
  FAILED: 'FAILED',
  RECOVERY_PENDING: 'RECOVERY_PENDING',
  EXPIRED: 'EXPIRED'
});

const TERMINAL_STATES = new Set([
  TRANSFER_STATE.STORED,
  TRANSFER_STATE.EXPIRED
]);

const ALLOWED_TRANSITIONS = Object.freeze({
  [TRANSFER_STATE.CREATED]: new Set([TRANSFER_STATE.ENCRYPTING, TRANSFER_STATE.FAILED]),
  [TRANSFER_STATE.ENCRYPTING]: new Set([TRANSFER_STATE.ENCRYPTED, TRANSFER_STATE.FAILED]),
  [TRANSFER_STATE.ENCRYPTED]: new Set([TRANSFER_STATE.RELAY_RECEIVING, TRANSFER_STATE.FAILED, TRANSFER_STATE.RECOVERY_PENDING]),
  [TRANSFER_STATE.RELAY_RECEIVING]: new Set([TRANSFER_STATE.RELAY_VERIFIED, TRANSFER_STATE.FAILED, TRANSFER_STATE.RECOVERY_PENDING]),
  [TRANSFER_STATE.RELAY_VERIFIED]: new Set([TRANSFER_STATE.STORAGE_RECEIVING, TRANSFER_STATE.FAILED, TRANSFER_STATE.RECOVERY_PENDING]),
  [TRANSFER_STATE.STORAGE_RECEIVING]: new Set([TRANSFER_STATE.STORED, TRANSFER_STATE.FAILED, TRANSFER_STATE.RECOVERY_PENDING]),
  [TRANSFER_STATE.FAILED]: new Set([TRANSFER_STATE.RECOVERY_PENDING, TRANSFER_STATE.EXPIRED]),
  [TRANSFER_STATE.RECOVERY_PENDING]: new Set([TRANSFER_STATE.ENCRYPTED, TRANSFER_STATE.RELAY_RECEIVING, TRANSFER_STATE.RELAY_VERIFIED, TRANSFER_STATE.STORAGE_RECEIVING, TRANSFER_STATE.FAILED, TRANSFER_STATE.EXPIRED]),
  [TRANSFER_STATE.STORED]: new Set(),
  [TRANSFER_STATE.EXPIRED]: new Set()
});

function assertTransition(from, to) {
  if (!Object.values(TRANSFER_STATE).includes(from) || !Object.values(TRANSFER_STATE).includes(to)) {
    throw new Error('Unknown transfer state.');
  }
  if (!ALLOWED_TRANSITIONS[from].has(to)) {
    throw new Error(`Illegal transfer state transition: ${from} -> ${to}`);
  }
}

function isTerminal(state) {
  return TERMINAL_STATES.has(state);
}

module.exports = {
  TRANSFER_STATE,
  ALLOWED_TRANSITIONS,
  assertTransition,
  isTerminal
};
